name: Where's My Bus?

nav:
  - name: Our Team
    href: "#team"
  - name: Deliverables
    href: "#deliverables"
  - name: Links
    href: "#links"

team:
  name: Team Bus
  members:
    - name: Becky Leslie
      cse_username: beleslie
      github_username: beleslie
    - name: Bryce Martz
      cse_username: bmartz
      github_username: bmartz
    - name: Daniel Houtsma
      cse_username: dhoutsma
      github_username: dhouty
    - name: David Li
      cse_username: lidav6
      github_username: lidav6
    - name: Dylan Whitlow
      cse_username: whitldy
      github_username: whitldy
    - name: Nick Bissiri
      cse_username: nbissiri
      github_username: nbissiri

deliverables:
  - - name: Status Report
      path: Bus_StatusReport1.pdf
    - name: Product Description
      path: Bus_ProductDescription.pdf
    - name: Use Cases
      path: Bus_UseCases.pdf
    - name: UI Diagrams
      path: Bus_UIDiagrams.pdf
    - name: Process Description
      path: Bus_ProcessDescription.pdf
  - - name: Status Report
      path: Bus_StatusReport2.pdf
    - name: Design Document
      path: Bus_DesignDocument.pdf
    - name: Presentation
      path: Bus_Presentation.pdf
  - - name: Status Report
      path: Bus_StatusReport3.pdf
    - name: Zero Feature Release
      path: wheresmybus-1.0.0.apk
    - name: User Documentation
      url: https://github.com/WheresMyBus/android/wiki/User-Documentation
    - name: Developer Documentation
      url: https://github.com/WheresMyBus/android/wiki/Developer-Documentation
  - - name: Status Report
      path: Bus_StatusReport4.pdf
  - - name: Status Report
      path: Bus_StatusReport5.pdf
    - name: Beta Release
      path: wheresmybus-1.1.0.apk
  - - name: Status Report
      path: Bus_StatusReport6.pdf
  - - name: Status Report
      path: Bus_StatusReport7.pdf
    - name: Feature Complete Release
      path: wheresmybus-1.2.0.apk
  - - name: User Testing
      path: Bus_UserTesting.pdf
    - name: Code Reviews
      path: Bus_CodeReviewDeliverable.pdf
    - name: Update Use Cases
      path: Bus_NewUseCases.pdf

links:
  - name: Product Website
    url: https://WheresMyBus.github.io/android
  - name: GitHub Organization
    url: https://github.com/WheresMyBus
  - name: Android Repository
    url: https://github.com/WheresMyBus/android
  - name: Where's My Bus API Repository
    url: https://github.com/WheresMyBus/api
  - name: OneBusAway API Repository
    url: https://github.com/WheresMyBus/onebusaway
  - name: Mailing List
    url: https://mailman1.u.washington.edu/mailman/listinfo/wheresmybus
