name: Where's My Bus?

nav:
  - name: About
    href: "#about"
  - name: Our Team
    href: "#team"
  - name: Deliverables
    href: "#deliverables"
  - name: Links
    href: "#links"

team:
  name: Team Bus
  members:
    - name: Becky Leslie
      cse_username: beleslie
      github_username: beleslie
    - name: Bryce Martz
      cse_username: bmartz
      github_username: bmartz
    - name: Daniel Houtsma
      cse_username: dhoutsma
      github_username: dhouty
    - name: David Li
      cse_username: lidav6
      github_username: lidav6
    - name: Dylan Whitlow
      cse_username: whitldy
      github_username: whitldy
    - name: Nick Bissiri
      cse_username: nbissiri
      github_username: nbissiri

deliverables:
  - - name: Status Report
      path: Bus_StatusReport1.pdf

links:
  - name: GitHub Organization
    url: https://github.com/WheresMyBus
  - name: Mailing List
    url: https://mailman1.u.washington.edu/mailman/listinfo/wheresmybus
